all:
	make -C 01_a
	make -C 02_a
	make -C 02_b
	make -C 02_c
	make -C 02_d
	make -C 02_e
	make -C 03
	make -C 04
	make -C 05
	make -C 06
	make -C 07
	make -C 08
	make -C 09
	make -C 11

test:
	make test -C 01_a
	make test -C 02_a
	make test -C 02_b
	make test -C 02_c
	make test -C 02_d
	make test -C 02_e
	make test -C 03
	make test -C 04
	make test -C 05
	make test -C 06
	make test -C 07
	make test -C 08
	make test -C 09
	make test -C 11

clean:
	make clean -C 01_a
	make clean -C 02_a
	make clean -C 02_b
	make clean -C 02_c
	make clean -C 02_d
	make clean -C 02_e
	make clean -C 03
	make clean -C 04
	make clean -C 05
	make clean -C 06
	make clean -C 07
	make clean -C 08
	make clean -C 09
	make clean -C 11
