all:
	make -C 02-instrucoes-basicas-aarch64
	make -C 03-instrucoes-aarch64-adicionais
	make -C 04-pilha-subrotinas
	make -C 05-aarch64-vf

test:
	make test -C 02-instrucoes-basicas-aarch64
	make test -C 03-instrucoes-aarch64-adicionais
	make test -C 04-pilha-subrotinas
	make test -C 05-aarch64-vf

clean:
	make clean -C 02-instrucoes-basicas-aarch64
	make clean -C 03-instrucoes-aarch64-adicionais
	make clean -C 04-pilha-subrotinas
	make clean -C 05-aarch64-vf
