all:
	make -C 02-instrucoes-basicas-aarch64
	make -C 03-instrucoes-aarch64-adicionais

test:
	make test -C 02-instrucoes-basicas-aarch64
	make test -C 03-instrucoes-aarch64-adicionais

clean:
	make clean -C 02-instrucoes-basicas-aarch64
	make clean -C 03-instrucoes-aarch64-adicionais
