all:
	make -C 01_a
	make -C 01_b
	make -C 01_c
	make -C 01_d
	make -C 03_a
	make -C 03_b
	make -C 03_c
	make -C 03_d_i
	make -C 03_d_ii
	make -C 03_e

test:
	make test -C 01_a
	make test -C 01_b
	make test -C 01_c
	make test -C 01_d
	make test -C 03_a
	make test -C 03_b
	make test -C 03_c
	make test -C 03_d_i
	make test -C 03_d_ii
	make test -C 03_e

clean:
	make clean -C 01_a
	make clean -C 01_b
	make clean -C 01_c
	make clean -C 01_d
	make clean -C 03_a
	make clean -C 03_b
	make clean -C 03_c
	make clean -C 03_d_i
	make clean -C 03_d_ii
	make clean -C 03_e
