all:
	make -C 01
	make -C 02
	make -C 06
	make -C 07
	make -C 08
	make -C 09

test:
	make test -C 01
	make test -C 02
	make test -C 06
	make test -C 07
	make test -C 08
	make test -C 09

clean:
	make clean -C 01
	make clean -C 02
	make clean -C 06
	make clean -C 07
	make clean -C 08
	make clean -C 09
