all:
	make -C VFE01
	make -C VFE02
	make -C VFE03
	make -C VFE04
	make -C VFE05
	make -C VFE06
	make -C VFE07
	make -C VFE08
	make -C VFE09

test:
	make test -C VFE01
	make test -C VFE02
	make test -C VFE03
	make test -C VFE04
	make test -C VFE05
	make test -C VFE06
	make test -C VFE07
	make test -C VFE08
	make test -C VFE09

clean:
	make clean -C VFE01
	make clean -C VFE02
	make clean -C VFE03
	make clean -C VFE04
	make clean -C VFE05
	make clean -C VFE06
	make clean -C VFE07
	make clean -C VFE08
	make clean -C VFE09
